sudo: false
language: go
script:
  - cd parallel
  - go test
go:
  - 1.11.x
  - 1.12.x
  - tip
env:
  global:
    - GORACE="halt_on_error=1"

notifications:
  email:
    recipients:
    - chengqinglian@qq.com
    on_success: change
    on_failure: always
