open:
    es: true
    log: false
    prometheus: false
monitorSystem:
    default:
        Namespace: "Test"
        Subsystemp: "testCount"
        Help: "test by yangqiao"
        Name: "test"
    es:
        Host: "rta-logger-2089710578.us-east-1.elb.amazonaws.com"
        Port: "9200"
        Index: "metric_test"
        Type: "counter"
        Interval: 10
