Open:
    Log: true
    Prometheus: false
    Elasticsearch: false
MonitorSystem:
    Default:
        Namespace: "Test"
        Subsystem: "testCount"
        Help: "test by yangqiao"
        Name: "test"
    Elasticsearch:
        Host: "rta-logger-2089710578.us-east-1.elb.amazonaws.com_error"
        Port: "9200"
        Index: "metric_test2"
        Type: "counter"
        Interval: "10"
    Log:
        LogPath : "./.testLog2"
        Interval: "10"
Metrics:
    Summary:
        Quantile50: 5
        Quantile90: 2
        Quantile99: 1

