Open:
    Log: false
    Prometheus: false
    Elasticsearch: true
MonitorSystem:
    Default:
        Namespace: "Test"
        Subsystem: "testCount"
        Help: "test by yangqiao"
        Name: "test"
    Elasticsearch:
        Host: "rta-logger-2089710578.us-east-1.elb.amazonaws.com"
        Port: "9200"
        Index: "metric_test2"
        Type: "counter"
        Interval: "10"
Metrics:
    Summary:
        Quantile50: 5
        Quantile90: 2
        Quantile99: 1

